In [17]:
import pandas as pd
import numpy as np

In [2]:
allrounder_name=pd.read_excel('All_Rounders.xlsx')

In [3]:
allrounder_name

,Player,Teams,Mat,Batting,Unnamed: 4,Unnamed: 5,Bowling,Unnamed: 7,Unnamed: 8
0,NaN,NaN,NaN,Inns,Runs,Avg,Overs,Wkts,Avg
1,S K Raina,"CSK, GUJ",205.0,200,5528,32.52,154.2,25,45.8
2,S R Watson,"RRO, RCB, CSK",145.0,141,3874,30.99,338.1,92,29.15
3,K A Pollard,MIN,189.0,171,3412,28.67,246,69,31.26
4,Y K Pathan,"RRO, KKR, SUN",174.0,154,3204,29.13,189.1,42,33.02
5,R A Jadeja,"RRO, KTK, CSK, GUJ",240.0,184,2959,27.4,638.1,160,30.4
6,G J Maxwell,"DDV, MIN, KXI, RCB",134.0,129,2771,24.74,157.2,37,35.22
7,Yuvraj Singh,"KXI, PWI, RCB, DDV, SUN, MIN",132.0,126,2750,24.77,144.5,36,29.92
8,H H Pandya,"MIN, GTI",137.0,128,2525,28.69,236.2,64,33.59
9,A D Russell,"DDV, KKR",127.0,105,2484,29.22,282.5,115,23.01
10,J H Kallis,"RCB, KKR",98.0,96,2427,28.55,290.2,65,35.28
11,D R Smith,"MIN, DCH, CSK, GUJ",91.0,89,2385,28.39,89.5,26,31.15
12,J-P Duminy,"MIN, DCH, DDV",83.0,77,2029,39.78,113,23,36.26
13,M P Stoinis,"KXI, RCB, DDV, LSG",96.0,88,1866,28.27,133.5,43,29.63
14,A R Patel,"KXI, DDV",150.0,113,1653,21.47,516.3,123,30.55
15,K H Pandya,"MIN, LSG",127.0,111,1647,22.56,353.4,76,34.29
16,D J J Bravo,"MIN, CSK, GUJ",161.0,113,1560,22.61,519.5,183,23.83
17,S P Narine,KKR,177.0,110,1534,17.04,679.1,180,25.39
18,M M Ali,"RCB, CSK",67.0,57,1162,22.78,126.2,35,25.51
19,I K Pathan,"KXI, DDV, SUN, RPS, GUJ",103.0,82,1139,21.49,340.3,80,33.11
20,R Tewatia,"RRO, KXI, DDV, GTI",93.0,65,1013,25.33,140.3,32,34.72
21,M C Henriques,"KKR, DDV, RCB, SUN, KXI",62.0,54,1000,27.78,158.2,42,30.69
22,J A Morkel,"CSK, RCB, DDV, RPS",91.0,68,974,24.35,287.1,85,27.75
23,A Symonds,"DCH, MIN",39.0,36,974,36.07,87.5,20,33.7
24,B A Stokes,"RPS, RRO, CSK",45.0,44,935,24.61,114.5,28,35.43
25,S M Curran,"KXI, CSK",59.0,48,883,25.23,196.5,58,32.76
26,S T R Binny,"MIN, RRO, RCB",95.0,68,880,19.13,99,22,34.45
27,Harbhajan Singh,"MIN, CSK, KKR",163.0,90,833,15.72,569.2,150,26.97
28,R Ashwin,"CSK, RPS, KXI, DDV, RRO",212.0,94,800,13.33,754,180,29.83
29,Shakib Al Hasan,"KKR, SUN",71.0,52,793,19.83,247.2,63,29.19
30,A D Mathews,"KKR, PWI, DDV",49.0,42,724,23.35,131.5,27,39.96
31,M R Marsh,"DCH, PWI, RPS, SUN, DDV",42.0,36,666,19.59,93.2,37,21.49
32,P P Chawla,"KXI, KKR, CSK, MIN",192.0,92,624,11.14,641.4,192,26.6
33,C H Morris,"CSK, RRO, DDV, RCB",81.0,51,618,22.07,286.4,95,24.16
34,Rashid Khan,"SUN, GTI",121.0,60,545,14.73,476.3,149,21.83
35,Shahbaz Ahmed,"RCB, SUN",55.0,37,536,19.14,89.3,21,39.86
36,J P Faulkner,"PWI, KXI, RRO, GUJ",60.0,45,527,21.08,204.3,59,30.14
37,P J Cummins,"KKR, DDV, SUN",58.0,41,515,19.81,219.5,63,30.52
38,No. of Records = 37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
names=allrounder_name['Player']

In [15]:
names.dropna()

1               S K Raina
2              S R Watson
3             K A Pollard
4              Y K Pathan
5              R A Jadeja
6             G J Maxwell
7            Yuvraj Singh
8              H H Pandya
9             A D Russell
10             J H Kallis
11              D R Smith
12             J-P Duminy
13            M P Stoinis
14              A R Patel
15             K H Pandya
16            D J J Bravo
17             S P Narine
18                M M Ali
19             I K Pathan
20              R Tewatia
21          M C Henriques
22             J A Morkel
23              A Symonds
24             B A Stokes
25             S M Curran
26            S T R Binny
27        Harbhajan Singh
28               R Ashwin
29        Shakib Al Hasan
30            A D Mathews
31              M R Marsh
32             P P Chawla
33             C H Morris
34            Rashid Khan
35          Shahbaz Ahmed
36           J P Faulkner
37            P J Cummins
38    No. of Records = 37
Name: Player, dtype: object

In [18]:
bowler = pd.read_csv('bowling_records.csv')
batter=pd.read_csv('batting_records.csv')

In [20]:
def get_player_records(bowler, batter, names):    
       
    bowler_records = bowler[bowler['name'].isin(names)]
    batter_records = batter[batter['name'].isin(names)]
    
    return bowler_records, batter_records

In [21]:
bowler_records, batter_records = get_player_records(bowler, batter, names)

In [22]:
from pathlib import Path
filepath_bowling = Path('all_bowling.csv') 
filepath_batting = Path('all_batting.csv') 

bowler_records.to_csv(filepath_bowling,index=False)
batter_records.to_csv(filepath_batting,index=False)

In [25]:
bowler_records = bowler_records.drop_duplicates(subset=['name'])

In [26]:
bowler_records

,name,team,span,matches,innings,overs,maidens,runs,wickets,best_bowling_figure,average,economy,strike_rate,4-fer,5-fer
5,R Ashwin,CSK/DC/KXIP/RPS/RR,2009-2024,212,208,4524,754.0,4,5369,180,4/34,29.82,7.12,25.13,1
10,Harbhajan Singh,CSK/KKR/MI,2008-2021,163,160,3416,569.2,6,4030,150,5/18,26.86,7.07,22.77,1
11,Rashid Khan,GT/SRH,2017-2024,121,121,2859,476.3,4,3252,149,4/24,21.82,6.82,19.18,2
60,Shakib Al Hasan,KKR/SRH,2011-2021,71,70,1484,247.2,1,1839,63,3/17,29.19,7.43,23.55,0

In [ ]:
batter